### ISSUE TITLE
diffrax; remove ode.py

### ISSUE THREAD

**Issue by benjaminpope** [SharmaLlama/ticktack#24]
@Jordan-Dennis has made great progress implementing the faster solvers in Diffrax; we can probbaly replace `odeint` with the Diffrax version, and delete `src/ode.py` from the main branch.

**Comment by Jordan-Dennis** [comment]
Ok finally, getting around to this, either tonight or tomorrow. Current plan is to enforce the `Dopri5` algorithm and the `AdjointBacksolve` gradient algorithm which is reverse mode. We will have to modify the interface to `CarbonBoxModel` to force the step-to points as a parameter.

**Comment by benjaminpope** [comment]
Bumping this thread @Jordan-Dennis - we should test whether Diffrax is worth switching out for the default Jax DP5 before we release 1.0

**Comment by Jordan-Dennis** [comment]
It is a lot more sophisticated, but a little slower (from memory). I do not think that it is orders of magnitude slower so it is probably worth switching so that stepping points can be specified. I will redo all this testing on the weekend because I am working on optics today.

**Comment by benjaminpope** [comment]
Yes indeed - ∂Lux is higher priority than ticktack for the moment!

**Comment by Jordan-Dennis** [comment]
So I have started looking into this and have hatched a rather interesting scheme. I understand that we want to keep things as stable as possible though so take this with a grain of salt. 

Problem: We want to be able to automatically pass the correct `step_ts` (step times) to the `diffrax` solver so that it is guaranteed to correctly solve the ode.

Solution 1: A typical feature of the production functions is that the centre and (approximate) widths of the event are given. We could enforce an order on the tuple, i.e. 
```
args : tuple = ()
    The parameters of the production function. The centre of the event and an 
    approximate measure of the width should be the 0th and 1st parameters. 
```
This is simple and requires the least amount of modification. However, it does seem open to things breaking quite easily. For example, people passing things in the wrong order, production functions that are defined by multiple peaks or continuous rises.

Solution 2: Pre-compute the production function and numerically find the correct step points. This isn't too hard to implement and in comparison to the evaluation of the ode-solver the time spent is probably insignificant. However, it is additional computation time, so is not ideal from a performance perspective. This solution is the best from a stability perspective. 

Solution 3 : Write the production functions as `equinox.Module`s with a parameter, `start_time` and a `get_start_time` method. This solution is radical and interesting, but not really for serious consideration. It would require major changes to the code that we do not want to make. 

@qingyuanzhang3, @SharmaLlama and @benjaminpope, let me know your thoughts on how we want to proceed. [This](https://docs.kidger.site/diffrax/api/stepsize_controller/) is the relevant doc's page for the `stepsize_controller` parameter.

**Comment by benjaminpope** [comment]
This is now implemented, and I've also made use of the `diffrax` feature to force `step_ts` to make sure we sample the spike no matter how short or small.
