### ISSUE TITLE
Inconsistent results in "Fitting multiple datasets using MultiFitter" tutorial

### ISSUE THREAD

**Issue by dfm** [SharmaLlama/ticktack#43]
When running the ["Fitting multiple datasets using MultiFitter"](https://sharmallama.github.io/ticktack/notebooks/02_MultiFitter/) tutorial, I find that when I make the final `chain_summary` plot, I get the following warnings:

```python
WARNING:chainconsumer:Parameter start date (yr) in chain Chain 0 is not constrained
WARNING:chainconsumer:Parameter duration (yr) in chain Chain 0 is not constrained
```

And no results are reported in the axis titles:

![82858979-345c-4fd6-bc6a-ba17c20e7992](https://user-images.githubusercontent.com/350282/221685404-4f49c7a1-594f-495a-8797-2a14f4ed97db.png)

The results do seem qualitatively similar, so this doesn't seem like a major issue, but it might be worth double checking that this isn't the result of something bigger!

ref: https://github.com/openjournals/joss-reviews/issues/5084

**Comment by benjaminpope** [comment]
Ah, well spotted. You see above that we added in a couple of lines

```python
samples = sampler.copy()
samples[:,1] = 10**samples[:,1] # duration not log duration
samples[:,-1] = 10**samples[:,-1] # area not log area
```

but didn't copy this at the bottom, and evidently didn't re-run the cell before committing the docs. This is because we switched to default parametrization of log duration and log spike production, rather than real-space. This is now fixed.
